### ISSUE TITLE
endgame not working

### ISSUE THREAD

**Issue by eraywax** [Dodging-Turtis/Dodging-Turtis#60]
Thats really good job guys 
I just play it but endgame not working

**Comment by Hardikag17** [comment]
Thanks, @eraywax !! actually, this is game is currently under development our team is working towards completing it soon.

**Comment by DineshBS44** [comment]
Hey @eraywax. I'm glad that you are checking out our game. We are still in the development phase and the work regarding the endgame is still in progress.
